from __future__ import annotations

from pii_sanitizer.core.detectors import HeaderDetector, RegexDetector


DEFAULT_RULES: list[dict[str, object]] = [
    {
        "id": "email",
        "entity_type": "EMAIL",
        "headers": ["email", "email_address", "mail", "contact_email"],
        "regex": r"\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}\b",
        "strategy": "mask",
        "confidence": 0.90,
        "header_confidence": 0.85,
    },
    {
        "id": "person_name",
        "entity_type": "PERSON_NAME",
        "headers": [
            "name",
            "full_name",
            "customer_name",
            "client_name",
            "employee_name",
            "respondent_name",
            "participant_name",
            "manager",
            "manager_name",
            "mgr",
            "mgr_name",
            "mngr",
            "mngr_name",
            "line_manager",
            "line_mgr",
            "direct_manager",
            "direct_mgr",
            "reporting_manager",
            "reporting_mgr",
            "people_manager",
            "people_mgr",
            "supervisor",
            "supervisor_name",
            "sup",
            "sup_name",
            "sv",
            "sv_name",
            "director",
            "director_name",
            "dir",
            "dir_name",
            "executive",
            "executive_name",
            "exec",
            "exec_name",
            "vp",
            "vp_name",
            "avp",
            "avp_name",
            "svp",
            "svp_name",
            "evp",
            "evp_name",
            "lead",
            "lead_name",
            "team_lead",
            "team_leader",
            "tl",
            "tl_name",
            "head",
            "head_name",
            "hod",
            "hod_name",
            "department_head",
            "dept_head",
            "business_head",
            "regional_manager",
            "regional_mgr",
            "area_manager",
            "area_mgr",
            "branch_manager",
            "branch_mgr",
            "country_manager",
            "country_mgr",
            "general_manager",
            "gm",
            "gm_name",
            "اسم",
            "الاسم",
            "اسم_العميل",
            "اسم_الموظف",
            "اسم_المدير",
            "المدير",
            "مدير",
            "المشرف",
            "مشرف",
            "الرئيس",
            "رئيس",
            "قائد_الفريق",
        ],
        "regex": r"\b(?:Ali|Mohammed|Mohammad|Ahmed|Abdullah|Abdulaziz|Khalid|Fahad|Saud|Sultan|Noura|Nora|Fatima|Sara|Mariam)(?:\s+(?:Al|Bin|Bint|Abdul|[A-Z][a-z]{2,})){1,3}\b",
        "strategy": "replace",
        "confidence": 0.72,
        "header_confidence": 0.92,
    },
    {
        "id": "phone",
        "entity_type": "PHONE",
        "headers": ["phone", "mobile", "mobile_number", "contact_number", "telephone", "رقم_الجوال", "رقم_الهاتف", "جوال", "هاتف"],
        "regex": r"(?<!\d)(?:\+?\d[\d\s().-]{7,}\d)(?!\d)",
        "strategy": "mask",
        "confidence": 0.70,
        "header_confidence": 0.80,
    },
    {
        "id": "private_url",
        "entity_type": "PRIVATE_URL",
        "headers": ["url", "website", "profile_url", "linkedin", "personal_url", "survey_url", "رابط", "الموقع"],
        "regex": r"\bhttps?://[^\s<>()]+|\bwww\.[^\s<>()]+",
        "strategy": "redact",
        "confidence": 0.84,
        "header_confidence": 0.90,
    },
    {
        "id": "private_date",
        "entity_type": "PRIVATE_DATE",
        "headers": ["dob", "date_of_birth", "birth_date", "birthday", "joining_date", "hire_date", "termination_date", "تاريخ_الميلاد"],
        "regex": r"\b(?:\d{4}[-/]\d{1,2}[-/]\d{1,2}|\d{1,2}[-/]\d{1,2}[-/]\d{2,4})\b",
        "strategy": "redact",
        "confidence": 0.68,
        "header_confidence": 0.93,
    },
    {
        "id": "private_address",
        "entity_type": "PRIVATE_ADDRESS",
        "headers": [
            "address",
            "home_address",
            "personal_address",
            "street_address",
            "mailing_address",
            "building",
            "villa",
            "apartment",
            "po_box",
            "postal_address",
            "عنوان",
            "العنوان",
            "عنوان_السكن",
        ],
        "regex": r"\b(?:P\.?O\.?\s*Box|PO\s*Box|Building|Villa|Apartment|Apt|Street|St\.|Road|Rd\.)\s+[A-Za-z0-9][A-Za-z0-9\s,.-]{2,}\b",
        "strategy": "redact",
        "confidence": 0.70,
        "header_confidence": 0.94,
    },
    {
        "id": "account_number",
        "entity_type": "ACCOUNT_NUMBER",
        "headers": ["account_number", "acct_number", "acct_no", "bank_account", "payroll_account", "رقم_الحساب", "حساب_بنكي"],
        "regex": r"\b[0-9]{8,18}\b",
        "strategy": "redact",
        "confidence": 0.60,
        "header_confidence": 0.94,
    },
    {
        "id": "secret",
        "entity_type": "SECRET",
        "headers": ["password", "passwd", "pwd", "secret", "token", "api_key", "access_key", "private_key", "كلمة_المرور"],
        "regex": r"\b(?:sk-[A-Za-z0-9_-]{16,}|[A-Za-z0-9_\-]{24,}\.[A-Za-z0-9_\-]{12,}\.[A-Za-z0-9_\-]{12,}|(?:api[_-]?key|token|secret|password)\s*[:=]\s*[A-Za-z0-9_\-./+=]{8,})\b",
        "strategy": "redact",
        "confidence": 0.86,
        "header_confidence": 0.96,
    },
    {
        "id": "gcc_phone",
        "entity_type": "PHONE_GCC",
        "headers": [
            "gcc_phone",
            "ksa_mobile",
            "saudi_mobile",
            "uae_mobile",
            "bahrain_mobile",
            "qatar_mobile",
            "kuwait_mobile",
            "oman_mobile",
            "رقم_الجوال",
            "الجوال",
            "الهاتف",
        ],
        "regex": r"(?<!\d)(?:\+|00)?(?:966|971|973|974|965|968)[-\s]?[0-9][0-9\s().-]{6,12}[0-9](?!\d)",
        "strategy": "mask",
        "confidence": 0.88,
        "header_confidence": 0.90,
    },
    {
        "id": "saudi_national_id",
        "entity_type": "NATIONAL_ID_SAUDI",
        "headers": ["national_id", "saudi_id", "ksa_id", "id_number", "رقم_الهوية", "الهوية", "هوية_وطنية"],
        "regex": r"\b1[0-9]{9}\b",
        "strategy": "redact",
        "confidence": 0.88,
        "header_confidence": 0.95,
    },
    {
        "id": "saudi_iqama",
        "entity_type": "RESIDENCY_ID_SAUDI_IQAMA",
        "headers": ["iqama", "iqama_number", "residency_id", "resident_id", "رقم_الإقامة", "رقم_الاقامة", "الإقامة", "الاقامة"],
        "regex": r"\b2[0-9]{9}\b",
        "strategy": "redact",
        "confidence": 0.88,
        "header_confidence": 0.95,
    },
    {
        "id": "gcc_iban",
        "entity_type": "BANK_ACCOUNT_IBAN_GCC",
        "headers": ["iban", "bank_iban", "account_iban", "رقم_الآيبان", "رقم_الايبان", "آيبان", "ايبان"],
        "regex": r"\b(?:SA[0-9]{2}[A-Z0-9]{18}|AE[0-9]{21}|BH[0-9]{2}[A-Z]{4}[A-Z0-9]{14}|KW[0-9]{2}[A-Z]{4}[0-9]{22}|QA[0-9]{2}[A-Z]{4}[A-Z0-9]{21}|OM[0-9]{2}[0-9]{3}[A-Z0-9]{16})\b",
        "strategy": "redact",
        "confidence": 0.92,
        "header_confidence": 0.95,
    },
    {
        "id": "gcc_passport",
        "entity_type": "PASSPORT_GCC",
        "headers": ["passport", "passport_number", "travel_document", "رقم_الجواز", "جواز_السفر", "الجواز"],
        "regex": r"\b[A-Z][0-9]{6,9}\b",
        "strategy": "redact",
        "confidence": 0.72,
        "header_confidence": 0.95,
    },
    {
        "id": "aadhaar",
        "entity_type": "NATIONAL_ID_AADHAAR",
        "headers": ["aadhaar", "aadhaar_number", "uid", "uidai"],
        "regex": r"\b[2-9][0-9]{3}\s?[0-9]{4}\s?[0-9]{4}\b",
        "strategy": "redact",
        "confidence": 0.85,
        "header_confidence": 0.95,
    },
    {
        "id": "uae_id",
        "entity_type": "NATIONAL_ID_UAE",
        "headers": ["uae_id", "emirates_id", "eid", "emirates_identity", "رقم_الهوية_الإماراتية", "الهوية_الإماراتية"],
        "regex": r"\b784[-\s]?[0-9]{4}[-\s]?[0-9]{7}[-\s]?[0-9]\b",
        "strategy": "redact",
        "confidence": 0.90,
        "header_confidence": 0.95,
    },
    {
        "id": "credit_card",
        "entity_type": "PAYMENT_CARD",
        "headers": ["card", "card_number", "credit_card", "debit_card", "pan"],
        "regex": r"\b(?:\d[ -]*?){13,19}\b",
        "strategy": "redact",
        "confidence": 0.65,
        "header_confidence": 0.85,
    },
]


def build_detectors(rules: list[dict[str, object]] | None = None) -> tuple[HeaderDetector, RegexDetector]:
    active_rules = rules or DEFAULT_RULES
    return HeaderDetector(active_rules), RegexDetector(active_rules)
